// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const fib = (n, end, a, b) => {
  if (n >= end) {
    return 0; // using 0 here because `return n` prints 188
  } else if (n % 2 === 0) {
    console.log(n); // should print 2, 8, 34
    return n + fib(a + b, end, b, a + b); // fib(1, 90, 1, 1)
  } else {
    return fib(a + b, end, b, a + b);
  }
};

// console.log(fib(0, 90, 0, 1)); // console.logged notes are for even fibs up to 90, returns 44
console.log(fib(0, 4000000, 0, 1)); // returns 4613732
